name = "SpineRegistry"
uuid = "3d0e5f26-04f2-4311-8ef0-0515aa5b4ff5"
repo = "https://github.com/Spine-project/SpineJuliaRegistry.git"

[packages]
0cda1612-498a-11e9-3c92-77fa82595a4f = { name = "SpineInterface", path = "S/SpineInterface" }
163584a9-52e1-4a4e-9262-a8c2d5456af4 = { name = "SpinePeriods", path = "S/SpinePeriods" }
b74cbf36-17f7-11e9-3430-fdc535b30a00 = { name = "SpineOpt", path = "S/SpineOpt" }
